#!/usr/bin/env python3

'''
@Author: Saksham Trivedi
@alias: - SK -
@Title: File-Handling
@Description: Script to Interact with filesystem
'''

# Actual funtion
def file_handling():

    # Opening File
    file = open ("ExampleFile.txt")

    # Reading File (Single Line) 
    print ("Reading Line...", end='\n\n')
    print (file.readline())

    # Reding File
    # Reads all the lines from the current line to the EOF)
    # Not from begning of a file
    print('\n\n')
    print ("Reading File from Current line...", end='\n\n')
    print (file.read())

    # Closing a File
    file.close()
    
    # Exit Status
    return 0

# Calling Fun
file_handling()