#!/usr/bin/env python3

'''
@Author: Saksham Trivedi
@alias: - SK -
@Title: File-Reading
@Description: Script to read from file
'''

# Actual funtion
def file_reading():

    # Opening File
    file = open ("ExampleFile.txt")

    # Reading File (Single Line) 
    print ("Reading Line...", end='\n\n')
    print (file.readline())

    # Reding File
    # Reads all the lines from the current line to the EOF)
    # Not from begning of a file
    print('\n\n')
    print ("Reading File from Current line...", end='\n\n')
    print (file.read())

    # Closing a File
    file.close()

    # Opening and automatically closing fil
    with open("ExampleFile.txt") as file:
        print (file.readline())

        print (file.read)

    # Iteration over file
    with open ("AnotherExample.txt") as file:
        for line in file:
            # Prints each Line
            print (line)
            
            # Print each lines in UPPERCASE
            print (line.upper())
            
            # Print each line with striping whitespace
            print (line.strip().upper())
            
    # To store a file
    file = open ("AnotherExample.txt")
    lines = file.readlines()
    file.close()
   
    # Strores list of lines (including whitespace) 
    print (lines)

    # Sorting Lines
    print (lines.sort())   

    # Exit Status
    return 0

# Calling Fun
file_reading()