#!/usr/bin/env python3

import shutil as sh
import psutil as pu

def check_disk_usage(disk):
    du = sh.disk_usage(disk)
    free = du.free / du.total * 100
    print ("Disk Usage: " + str(int(free)) + "%")
    return free > 20

def check_cpu_uage():
    usage = pu.cpu_percent(1)
    print ("CPU Usage: " + str(usage) + "%")
    return usage < 75

if not check_disk_usage("/") or not check_cpu_uage():
    print ("ERROR!")
else:
    print ("Everything is OK!")