#!/usr/bin/env python3

'''
@Author: Saksham Trivedi
@alias: - SK -
@Title: sys-insights
@Description: Script to show disk and CPU usage in %
'''

import shutil as sh
import psutil as pu

# System Insights
def sys_insights():

    # Disk Usage
    def check_disk_usage(disk):
        du = sh.disk_usage(disk)
        free = du.free / du.total * 100
        print ("Disk Usage: " + str(int(free)) + "%")
        return free > 20

    # CPU Usage
    def check_cpu_uage():
        usage = pu.cpu_percent(1)
        print ("CPU Usage: " + str(usage) + "%")
        return usage < 75

    # If not found
    if not check_disk_usage("/") or not check_cpu_uage():
        print ("ERROR!")
    else:
        print ("Everything is OK!")

    # exit status
    return 0

# Fun calling
sys_insights()