#!/usr/bin/python3

'''
@Author: Saksham Trivedi
@alias: SK
@Email: trivedisaksham@gmail.com
@Github: https://github.com/SK-here
@Description: A script to send email.
'''

import os
import smtplib
from datetime import datetime


############################################## READIN A LOG FILE SECTION ###########################################################



############################################## EMAIL SECTION #########################################################################

# Imports Passwd from env var
EMAIL_ADDRESS = os.environ.get('EMAIL_USER')
EMAIL_PASSWD = os.environ.get('EMAIL_PASS')


from email.message import EmailMessage 

msg = EmailMessage()

msg['Subject'] = 'Test Message'
msg['From'] = EMAIL_ADDRESS
msg['To'] = 'trivedianuj171@gmail.com'
msg['Cc'] = ['trivedisaksham@gmail.com', 'mistersolo009@gmail.com', 'linuxadminjbp@vsndirect.com']
msg.set_content('''
                This is a content of a message
                ''')

with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
    smtp.login(EMAIL_ADDRESS, EMAIL_PASSWD) 

    smtp.send_message(msg)
